#!/bin/csh
#------------------------------------------------------------
# Provision TrueOS FreeBSD instance as a dev env template
#
# Version 0.1.0 13 May 2018 Dave Nicolette
#------------------------------------------------------------

cd ~/bootstrap-trueos-freebsd-dev-base

printf "Configuring csh...\n
printf "  ...copying .cshrc file\n" 
cp scripts/.cshrc ~/.
printf "  ...copying .login file\n"
cp scripts/.login ~/.

printf "Installing Python 2 and 3 packages...\n" 
printf "  ...installing python\n"
sudo pkg install python 
sudo python -m pip install -U pip
printf "  ...installing python3\n"
sudo pkg install python3
sudo python3 -m pip install -U pip

printf "Installing Ruby 2.4...\n"
set ruby="`pkg search ruby | grep '^ruby-2.4' | cut -d ' ' -f 1`"
printf "  ...installing package $ruby\n"
sudo pkg install "$ruby"


printf "Installing OpenBox window manager...\n"
printf "  ...installing package openbox\n"
sudo pkg install openbox 
printf "  ...copying configuration files\n" 
mkdir -p ~/.config/openbox
cp openbox/menu.xml ~/.config/openbox/.
cp openbox/rc.xml ~/.config/openbox/.

printf "Installing urxvt terminal emulator...\n"
printf "  ...installing package x11/rxvt-unicode\n"
sudo pkg install x11/rxvt-unicode
printf "  ...initializing .Xdefaults settings for urxvt\n"
echo "URxvt.termName: xterm-256color" >> ~/.Xdefaults 

printf "Installing NeoVim text editor...\n"
printf "  ...installing package neovim\n"
sudo pkg install neovim 
printf "  ...installing Python and Python3 support for NeoVim plugins\n"
pip2 install --user neovim
pip3 install --user neovim
printf "  ...creating NeoVim subdirectories under ~/.config\n"
mkdir -p ~/.config/nvim/autoload 
mkdir -p ~/.config/nvim/bundle 
mkdir -p ~/.config/nvim/pack/vendor/start
mkdir -p ~/.config/nvim/after/indent 
cp neovim/init.vim ~/.config/nvim/.
printf "  ...copying NeoVim configuration file\n"
mkdir -p ~/.config/nvim/autoload 
